#include "../game_rules.h"
#include "../json.h"
#include "catch.hpp"
#include <iostream>

using json = nlohmann::json;

TEST_CASE("Parse GameRules") {
  SECTION("parse game rules") {
    std::string weh = R"({"starting_units":["general","worker","worker","worker","worker","worker"],"unit_cap":50,"unit_kinds":[{"attack":[1,3,1],"colour":"BLUE","cost":9,"health":3,"id":"avatar","image":"avatar.png","label":"A","name":"Avatar","tech":{"blue":3,"green":1,"red":5},"tiles":[0,0,0,1],"width":2},{"attack":[1,1],"colour":"RED","cost":5,"health":2,"id":"commando","image":"default_red.png","label":"c","name":"Commando","tech":{"blue":2,"red":3},"tiles":[0,0],"width":1},{"attack":[],"colour":"GREEN","cost":5,"health":1,"id":"fort","image":"default_green.png","label":"F","name":"Fort","tech":{"blue":2,"green":3},"tiles":[0,0,0,1,1,0,1,1],"width":4},{"attack":[2],"colour":"BLACK","cost":0,"health":5,"id":"general","image":"commander.png","label":"G","name":"General","tech":null,"tiles":[0,0],"width":1},{"attack":[1],"colour":"RED","cost":2,"health":1,"id":"grunt","image":"the_grunt.png","label":"g","name":"Grunt","tech":{},"tiles":[0,0],"width":1},{"attack":[1],"colour":"RED","cost":2,"health":3,"id":"insurgent","image":"insurgent.png","label":"i","name":"Insurgent","tech":{"blue":1,"green":1,"red":2},"tiles":[0,0],"width":1},{"attack":[2],"colour":"RED","cost":4,"health":2,"id":"ogre","image":"the_ogre.png","label":"o","name":"Ogre","tech":{"green":2,"red":2},"tiles":[0,0,1,0],"width":2},{"attack":[],"colour":"BLUE","cost":9,"font":4,"health":2,"id":"paragon","image":"paragon.png","label":"p","name":"Paragon","tech":{"blue":7,"green":1,"red":1},"tiles":[0,0],"width":1},{"attack":[2],"colour":"GREEN","cost":5,"health":4,"id":"shrek","image":"shrek.png","label":"S","name":"Shrek","tech":{"green":3,"red":2},"tiles":[0,0,1,0,2,0],"width":3},{"attack":[1],"colour":"BLUE","cost":3,"health":1,"id":"soldier","image":"default_blue.png","label":"s","name":"Soldier","tech":{"blue":2,"red":1},"tiles":[0,0],"width":1},{"attack":[2],"colour":"BLUE","cost":9,"health":10,"id":"tank","image":"tank.png","label":"K","name":"Tank","tech":{"blue":3,"green":5,"red":1},"tiles":[1,0,0,1,1,1,2,1,0,2,1,2,2,2],"width":7},{"attack":[4],"colour":"RED","cost":5,"health":2,"id":"troll","image":"the_troll.png","label":"T","name":"Troll","tech":{"red":5},"tiles":[0,0,1,0],"width":2},{"attack":[1],"colour":"GREEN","cost":2,"health":1,"id":"turret","image":"cutie.png","label":"t","name":"Turret","tech":{"green":1},"tiles":[0,0,0,1],"width":2},{"attack":[],"colour":"GREEN","cost":1,"health":2,"id":"wall","image":"wall.png","label":"w","name":"Wall","shields":1,"tech":{"green":1},"tiles":[0,0],"width":1},{"attack":[],"colour":"GREEN","cost":3,"health":2,"id":"wide_wall","image":"wide_wall.png","label":"W","name":"Wide Wall","tech":{"green":3},"tiles":[0,0,1,0,2,0,3,0],"width":4},{"attack":[],"colour":"BLUE","cost":3,"font":1,"health":1,"id":"worker","image":"font_b.png","label":"b","name":"Worker","shields":2,"tech":{},"tiles":[0,0],"width":1}]})";
    json weh_parsed = json::parse(weh);
  }
}
